<a href="https://colab.research.google.com/github/angakishor/Python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

a = np.array([1, 2, 3])
b = np.zeros((2, 3))      # 2x3 matrix of zeros
c = np.ones((3, 3))       # 3x3 matrix of ones
d = np.arange(1, 10, 2)   # [1, 3, 5, 7, 9]
e = np.full((2, 2), 7)                 # Fill with specific value
f = np.eye(4)                          # Identity matrix
g = np.random.rand(2, 2)               # Random values [0, 1)
h = np.arange(0, 10, 2)                # [0, 2, 4, 6, 8]
i = np.linspace(0, 1, 5)               # [0. , 0.25, 0.5, 0.75, 1.]


In [9]:
print(a)

print(b)

print(c)

print(d)

print(e)

print(f)

print(g)

print(h)

print(i)

[1 2 3]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7 9]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.70998    0.12307551]
 [0.77552263 0.24967856]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [12]:

a.dtype


dtype('int64')

In [13]:
a.ndim

1

In [14]:
a.size

3

In [15]:
a.shape

(3,)

In [3]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x + y)  # [5, 7, 9]
print(np.mean(x))  # average
print(np.dot(x, y))  # dot product


[5 7 9]
2.0
32


In [16]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1])            # 20
print(arr[1:4])          # [20, 30, 40]

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix[1, 2])      # 6
print(matrix[:, 1])      # [2 5] (all rows, column 1)


20
[20 30 40]
6
[2 5]


In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)       # [5 7 9]
print(a - b)       # [-3 -3 -3]
print(a * b)       # [4 10 18]
print(a / b)       # [0.25 0.4 0.5]
print(a ** 2)      # [1 4 9]


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [18]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print(np.dot(x, y))   # Matrix multiplication


[[19 22]
 [43 50]]


In [19]:
a = np.array([[1, 2], [3, 4], [5, 6]])

print(a.reshape(2, 3))      # Change shape to 2x3
print(a.flatten())          # Flatten to 1D array


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [20]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])

print(np.vstack((a, b)))   # Vertical stack
print(np.hstack((a, b)))   # Horizontal stack


[[1 2]
 [3 4]]
[[1 2 3 4]]


In [21]:
arr = np.array([10, 20, 30, 40])
print(arr > 25)            # [False False  True  True]
print(np.where(arr > 25))  # Indices where condition is True


[False False  True  True]
(array([2, 3]),)


In [22]:
a = np.array([1, 2, 3])
b = a.copy()     # Independent copy
c = a.view()     # Shares data

a[0] = 100
print(b)         # [1 2 3]
print(c)         # [100 2 3]


[1 2 3]
[100   2   3]


In [23]:
a = np.array([1, 2, 3])
b = 2
print(a + b)    # [3 4 5]


[3 4 5]


In [25]:
arr=[10,5,7,11,5,35,19,7]
a=np.unique(arr)      # Unique values
b=np.sort(arr)        # Sort array
c=np.argmax(arr)      # Index of max value
d=np.argmin(arr)      # Index of min value
e=np.clip(arr, 10, 20) # Limit values between 10 and 20
print(a)
print(b)
print(c)
print(d)
print(e)

[ 5  7 10 11 19 35]
[ 5  5  7  7 10 11 19 35]
5
1
[10 10 10 11 10 20 19 10]


In [27]:
print(np.random.seed(42))           # For reproducibility
print(np.random.randint(0, 10, 5))  # 5 random integers between 0–9
print(np.random.normal(0, 1, 5))    # Normal distribution


None
[6 3 7 4 6]
[-0.91682684 -0.12414718 -2.01096289 -0.49280342  0.39257975]
